In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [3]:
import numpy as np

In [4]:
!pip install numpy

คือการ install ชุดคำสั่ง

In [5]:
np.__version__

'1.19.5'

In [6]:
a = np.array([1,2,3,4,5,6,7])   
a

array([1, 2, 3, 4, 5, 6, 7])

In [7]:
a = np.array([[1,2,3] , [4,5,6] , [7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
a = np.array([1,2,3,4,5,6,7])   
a[0]

1

In [9]:
a[2:5]

array([3, 4, 5])

In [10]:
L = [1,2,3,4,5,6,7]
L[0]

1

In [11]:
L[2:5]

[3, 4, 5]

In [12]:
a[:6]

array([1, 2, 3, 4, 5, 6])

In [13]:
L[:6]

[1, 2, 3, 4, 5, 6]

In [14]:
a[3:]

array([4, 5, 6, 7])

In [15]:
a[-1]

7

คือตำแหน่งสุดท้าย

In [16]:
a[2:-3]

array([3, 4])

In [17]:
a[-5:]

array([3, 4, 5, 6, 7])

In [18]:
a[-5:-1]

array([3, 4, 5, 6])

In [19]:
a[-2:2]

array([], dtype=int64)

In [20]:
np.size(a)

7

In [21]:
np.shape(a)

(7,)

vector 

In [22]:
a = a.reshape(1,7)
np.shape(a)

(1, 7)

In [23]:
a

array([[1, 2, 3, 4, 5, 6, 7]])

In [31]:
a[a[3]]

IndexError: index 3 is out of bounds for axis 0 with size 1

เอามาซ้อนกัน a3 + a = a ตัวที่ 4

In [25]:
a

array([[1, 2, 3, 4, 5, 6, 7]])

In [ ]:
a.sort
a

In [ ]:
sorted(a , reverse=True)

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

In [ ]:
L = [[1,2,3] , [4,5,6] , [7,8,9]]
L

In [ ]:
a[0,0]

แถวที่ 0 หลักที่ 0

In [ ]:
L[0][0]

In [ ]:
a[1,:]

In [ ]:
a[1]

In [ ]:
a[:,-1]

In [28]:
L[:][0]

1

In [26]:
a[:,1] = 0
a

array([[1, 0, 3, 4, 5, 6, 7]])

In [29]:
a[1,:] = 0
a

IndexError: index 1 is out of bounds for axis 0 with size 1

In [ ]:
a[0:2,:] = 8
a

In [ ]:
a.shape

In [ ]:
a.size

In [ ]:
a.ndim

ndim คือหาว่ามีกี่ dimension

In [ ]:
np_mix_matrix = np.array([['one',2],['three',4],['five',6]])
np_mix_matrix

In [ ]:
a = np.array(np_mix_matrix[:,1], dtype=int)
a

In [ ]:
a = np.ones((10))
a

In [ ]:
c = np.full((2,2) ,8)
c

In [ ]:
a = np.ones((5,5))*8
a

In [ ]:
d = np.eye(2)
d

In [ ]:
np.matmul(c,d)

In [ ]:
np.empty((20,20))

In [ ]:
rng = np.random.RandomState(0)
np.random.rand(5)

rng = np.random.RandomState(0) คือให้มัน ran ได้ค่าเดิม

เลขที่สุ่มจะอยู่ช่วง 0-1

In [ ]:
np.round(np.random.rand()*10)

In [ ]:
[np.round(np.random.rand()*10) for item in range (10)]

In [42]:
np.random.randint(5)

1

In [ ]:
np.random.seed = 0
[np.random.randint(5)for item in range (10)]

In [ ]:
np.round(np.random.rand(5,5))

ข้าม ex.1

In [32]:
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5)

array([9, 2, 3, 8, 4])

In [33]:
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5, replace=False)

array([6, 7, 2, 5, 4])

In [34]:
np_matrix = np.round(np.random.rand(10000,5))
np_matrix 

array([[0., 1., 1., 1., 1.],
       [0., 0., 0., 1., 1.],
       [1., 1., 0., 1., 1.],
       ...,
       [1., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
idx_choose = np.random.choice(1000,100, replace=False)
idx_choose

In [ ]:
np_matrix_choose = np_matrix[idx_choose,:]
np_matrix_choose

# > ex.2
> Randomly create a matrix of size (10, 5) then randomly assign values of 0 and 1 to the last column of this matrix.

In [44]:
np_matrix = np.random.rand(10,5)
np_matrix[:,4] = np.round(np.random.rand(1,10))
np_matrix #สุ่มเลข 10 บรรทัด 5 คอลั่ม แล้วแปลงให้คอลั่มสุดท้ายเป็น 0-1

array([[0.59196619, 0.68181807, 0.06945717, 0.05279381, 1.        ],
       [0.17103153, 0.48199073, 0.97303894, 0.60445232, 0.        ],
       [0.53596845, 0.13426255, 0.03868787, 0.8787036 , 1.        ],
       [0.16316868, 0.27245006, 0.58388063, 0.02450487, 0.        ],
       [0.48906554, 0.82328996, 0.47269034, 0.1347517 , 0.        ],
       [0.00839941, 0.61461798, 0.8392288 , 0.87008575, 0.        ],
       [0.55655569, 0.72257199, 0.15464285, 0.58451847, 1.        ],
       [0.12257361, 0.11633678, 0.26837118, 0.35093331, 0.        ],
       [0.23093237, 0.07978322, 0.40863221, 0.89962565, 1.        ],
       [0.23220671, 0.55584558, 0.88109947, 0.00522972, 0.        ]])

In [36]:
np_matrix = np.random.randint(3,size = (5,5))
np_matrix

array([[0, 2, 1, 1, 1],
       [0, 0, 0, 2, 2],
       [1, 2, 0, 2, 1],
       [2, 2, 2, 0, 0],
       [2, 0, 0, 2, 2]])

In [38]:
i,j = np.where(np_matrix == 2)

In [39]:
i

array([0, 1, 1, 2, 2, 3, 3, 3, 4, 4, 4])

In [ ]:
j

In [ ]:
i,j = np.where(np_matrix == 2)
[(i[ii],j[ii]) for i in range(len(i))]

# ex.3
Why we cannot use this index ? Please fix it !!


In [54]:
idx = [1,2,3,4,5]
np_matrix[np.size(idx)-1,:] 

array([0, 1, 0, 0, 1])

In [51]:
np_matrix = np.random.randint(3,size = (5,5))
np_matrix 

array([[2, 0, 0, 1, 2],
       [2, 2, 0, 1, 1],
       [1, 2, 0, 1, 1],
       [2, 2, 2, 0, 2],
       [0, 2, 1, 2, 2]])

แบบเก่า

In [52]:
rng = np.random.RandomState(0)
np_matrix = rng.randint(3,size = (5,5))
np_matrix

array([[0, 1, 0, 1, 1],
       [2, 0, 2, 0, 0],
       [0, 2, 1, 2, 2],
       [0, 1, 1, 1, 1],
       [0, 1, 0, 0, 1]])

random แบบใหม่

In [55]:
np_matrix = np.delete(np_matrix,[1,2],1)
np_matrix

array([[0, 1, 1],
       [2, 0, 0],
       [0, 2, 2],
       [0, 1, 1],
       [0, 0, 1]])

ลบแถวที่ 1,2 ออก 0 ที่ตามท้ายหมายถึงลบแถว 1 ที่ตามท้ายหมายถึงลบคอลั่ม

In [ ]:
np_matrix = np.random.randint(10,size = (5,5))
np_matrix

In [ ]:
np_matrix[(np_matrix == 2)] = 99
np_matrix

ตำแหน่งไหนเป้น 2 จะ true และ ทำให้ 2=99

# Ex.4
Randomly create a data matrix of 10 samples with 5 features. 

In [57]:
random = np.random.randint(10,size= (10,5))
random

array([[0, 3, 5, 5, 0],
       [9, 9, 9, 5, 9],
       [8, 9, 2, 3, 1],
       [5, 7, 5, 4, 8],
       [9, 1, 3, 6, 1],
       [9, 5, 9, 1, 8],
       [1, 9, 8, 7, 0],
       [1, 0, 8, 3, 7],
       [4, 6, 2, 1, 2],
       [0, 2, 4, 4, 2]])

In [58]:
vector = np.random.randint(2,size = 10)
vector

array([1, 0, 1, 1, 0, 1, 0, 0, 1, 0])

In [59]:
random[np.where(vector == 0)]

array([[9, 9, 9, 5, 9],
       [9, 1, 3, 6, 1],
       [1, 9, 8, 7, 0],
       [1, 0, 8, 3, 7],
       [0, 2, 4, 4, 2]])

In [60]:
random[np.where(vector == 1)]

array([[0, 3, 5, 5, 0],
       [8, 9, 2, 3, 1],
       [5, 7, 5, 4, 8],
       [9, 5, 9, 1, 8],
       [4, 6, 2, 1, 2]])